In [22]:
import pandas as pd

In [32]:
df = pd.read_csv('data/ssp_model_results/iran/iran.csv')
df

,primary_id,region,time_period,area_agrc_crops_bevs_and_spices,area_agrc_crops_cereals,area_agrc_crops_fibers,area_agrc_crops_fruits,area_agrc_crops_herbs_and_other_perennial_crops,area_agrc_crops_nuts,area_agrc_crops_other_annual,...,yf_agrc_fruits_tonne_ha,yf_agrc_herbs_and_other_perennial_crops_tonne_ha,yf_agrc_nuts_tonne_ha,yf_agrc_other_annual_tonne_ha,yf_agrc_other_woody_perennial_tonne_ha,yf_agrc_pulses_tonne_ha,yf_agrc_rice_tonne_ha,yf_agrc_sugar_cane_tonne_ha,yf_agrc_tubers_tonne_ha,yf_agrc_vegetables_and_vines_tonne_ha
0,0,iran,7,2.354342e+06,5.236903e+06,1.086620e+06,2.832254e+06,3.654765e+06,1.994651e+06,2.638574e+06,...,12.291287,3.021928,1.207774,1.122455,1.862022,2.213576,3.954868,76.331220,25.149791,13.691656
1,0,iran,8,2.379435e+06,5.292717e+06,1.098201e+06,2.862440e+06,3.693717e+06,2.015910e+06,2.666696e+06,...,12.291287,3.021928,1.207774,1.122455,1.862022,2.213576,3.954868,76.331220,25.149791,13.691656
2,0,iran,9,2.404280e+06,5.347981e+06,1.109668e+06,2.892328e+06,3.732284e+06,2.036959e+06,2.694540e+06,...,12.291287,3.021928,1.207774,1.122455,1.862022,2.213576,3.954868,76.331220,25.149791,13.691656
3,0,iran,10,2.428879e+06,5.402700e+06,1.121021e+06,2.921921e+06,3.770472e+06,2.057801e+06,2.722110e+06,...,12.291287,3.021928,1.207774,1.122455,1.862022,2.213576,3.954868,76.331220,25.149791,13.691656
4,0,iran,11,2.453237e+06,5.456879e+06,1.132263e+06,2.951223e+06,3.808283e+06,2.078437e+06,2.749407e+06,...,12.291287,3.021928,1.207774,1.122455,1.862022,2.213576,3.954868,76.331220,25.149791,13.691656
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
111,71071,iran,31,2.439077e+06,6.800219e+06,1.125728e+06,2.934189e+06,3.786303e+06,2.066441e+06,2.733539e+06,...,14.339834,3.525582,1.409069,1.309531,2.172359,2.582506,4.614012,89.053090,29.341422,15.973599
112,71071,iran,32,2.437148e+06,6.856003e+06,1.124838e+06,2.931868e+06,3.783308e+06,2.064806e+06,2.731376e+06,...,14.442262,3.550765,1.419134,1.318884,2.187876,2.600952,4.646970,89.689183,29.551004,16.087696
113,71071,iran,33,2.434989e+06,6.910957e+06,1.123841e+06,2.929271e+06,3.779956e+06,2.062977e+06,2.728956e+06,...,14.544689,3.575948,1.429199,1.328238,2.203393,2.619399,4.679927,90.325277,29.760585,16.201793
114,71071,iran,34,2.432606e+06,6.965083e+06,1.122741e+06,2.926404e+06,3.776257e+06,2.060958e+06,2.726286e+06,...,14.647117,3.601131,1.439263,1.337592,2.218910,2.637845,4.712884,90.961370,29.970167,16.315890
115,71071,iran,35,2.430007e+06,7.018312e+06,1.121542e+06,2.923277e+06,3.772222e+06,2.058756e+06,2.723373e+06,...,14.749544,3.626313,1.449328,1.346946,2.234426,2.656292,4.745841,91.597464,30.179749,16.429988

In [23]:
df_attr_strat = pd.read_csv('data/ssp_model_results/iran/ATTRIBUTE_STRATEGY_new.csv')
df_attr_strat.head()

,strategy_id,strategy_code,strategy,description,transformation_specification,baseline_strategy_id
0,0,BASE,Strategy TX:BASE,NaN,TX:BASE,1
1,1009,LNDU:PLUR,Singleton - Default Value - LNDU: Partial land...,NaN,TX:LNDU:PLUR,0
2,1017,SOIL:DEC_LIME_APPLIED,Singleton - Default Value - SOIL: Improve lime...,NaN,TX:SOIL:DEC_LIME_APPLIED,0
3,1019,SOIL:DEC_N_APPLIED,Singleton - Default Value - SOIL: Improve fert...,NaN,TX:SOIL:DEC_N_APPLIED,0
4,1021,AF:ALL,Sectoral Composite - AFOLU,All (unique by transformer) AFOLU transformations,TX:AGRC:DEC_CH4_RICE|TX:AGRC:DEC_EXPORTS|TX:AG...,0

In [24]:
df_out = pd.read_csv('output/cost_benefit_results.csv')
df_out.head()

,strategy_code,future_id,region,time_period,difference_variable,difference_value,variable,value
0,SCOE:DEC_DEMAND_HEAT,0,iran,7,pop_lvst_buffalo,0.0,cb:lvst:lvst_value:livestock_produced:buffalo,0.0
1,SCOE:DEC_DEMAND_HEAT,0,iran,8,pop_lvst_buffalo,0.0,cb:lvst:lvst_value:livestock_produced:buffalo,0.0
2,SCOE:DEC_DEMAND_HEAT,0,iran,9,pop_lvst_buffalo,0.0,cb:lvst:lvst_value:livestock_produced:buffalo,0.0
3,SCOE:DEC_DEMAND_HEAT,0,iran,10,pop_lvst_buffalo,973.0,cb:lvst:lvst_value:livestock_produced:buffalo,252980.0
4,SCOE:DEC_DEMAND_HEAT,0,iran,11,pop_lvst_buffalo,1380.0,cb:lvst:lvst_value:livestock_produced:buffalo,358800.0

In [25]:
df_out.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 143028 entries, 0 to 143027
Data columns (total 8 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   strategy_code        143028 non-null  object
 1   future_id            143028 non-null  int64
 2   region               143028 non-null  object
 3   time_period          143028 non-null  int64
 4   difference_variable  143028 non-null  object
 5   difference_value     141652 non-null  float64
 6   variable             143028 non-null  object
 7   value                141781 non-null  float64
dtypes: float64(2), int64(2), object(4)
memory usage: 8.7+ MB

In [29]:
strategy_codes = list(df_out.strategy_code.unique())
strategy_codes.sort()
strategy_codes

['AGRC:DEC_CH4_RICE',
 'ENTC:TARGET_RENEWABLE_ELEC',
 'FGTV:DEC_LEAKS',
 'FGTV:INC_FLARE',
 'IPPU:DEC_CLINKER',
 'IPPU:DEC_DEMAND',
 'IPPU:DEC_N2O',
 'IPPU:DEC_OTHER_FCS',
 'IPPU:DEC_PFCS',
 'LVST:DEC_ENTERIC_FERMENTATION',
 'SCOE:DEC_DEMAND_HEAT',
 'SCOE:INC_EFFICIENCY_APPLIANCE',
 'TRWW:INC_CAPTURE_BIOGAS',
 'WALI:INC_TREATMENT_INDUSTRIAL',
 'WALI:INC_TREATMENT_RURAL',
 'WALI:INC_TREATMENT_URBAN',
 'WASO:INC_ANAEROBIC_AND_COMPOST',
 'WASO:INC_CAPTURE_BIOGAS',
 'WASO:INC_ENERGY_FROM_BIOGAS',
 'WASO:INC_ENERGY_FROM_INCINERATION',
 'WASO:INC_LANDFILLING',
 'WASO:INC_RECYCLING']

In [30]:
og_strategies = list(df_attr_strat[df_attr_strat.strategy_id > 7000].strategy_code.sort_values())
og_strategies

['AGRC:DEC_CH4_RICE',
 'AGRC:DEC_EXPORTS',
 'AGRC:DEC_LOSSES_SUPPLY_CHAIN',
 'AGRC:INC_CONSERVATION_AGRICULTURE',
 'AGRC:INC_PRODUCTIVITY',
 'CCSQ:INC_CAPTURE',
 'ENTC:DEC_LOSSES',
 'ENTC:TARGET_CLEAN_HYDROGEN',
 'ENTC:TARGET_RENEWABLE_ELEC',
 'FGTV:DEC_LEAKS',
 'FGTV:INC_FLARE',
 'INEN:INC_EFFICIENCY_ENERGY_HIGHEST',
 'INEN:INC_EFFICIENCY_PRODUCTION',
 'INEN:SHIFT_FUEL_HEAT',
 'IPPU:DEC_CLINKER',
 'IPPU:DEC_DEMAND',
 'IPPU:DEC_HFCS_HIGHEST',
 'IPPU:DEC_N2O',
 'IPPU:DEC_OTHER_FCS',
 'IPPU:DEC_PFCS',
 'LNDU:DEC_DEFORESTATION',
 'LNDU:DEC_SOC_LOSS_PASTURES',
 'LNDU:INC_REFORESTATION',
 'LNDU:INC_SILVOPASTURE',
 'LSMM:INC_CAPTURE_BIOGAS',
 'LSMM:INC_MANAGEMENT_CATTLE_PIGS',
 'LSMM:INC_MANAGEMENT_OTHER',
 'LSMM:INC_MANAGEMENT_POULTRY',
 'LVST:DEC_ENTERIC_FERMENTATION',
 'LVST:DEC_EXPORTS',
 'LVST:INC_PRODUCTIVITY',
 'PFLO:INC_HEALTHIER_DIETS',
 'PFLO:INC_IND_CCS',
 'SCOE:DEC_DEMAND_HEAT',
 'SCOE:INC_EFFICIENCY_APPLIANCE',
 'SCOE:SHIFT_FUEL_HEAT',
 'SOIL:DEC_LIME_APPLIED_HIGHEST',
 'SOIL:DEC_N_APPLIED_HIGHEST',
 'TRDE:DEC_DEMAND',
 'TRNS:INC_EFFICIENCY_ELECTRIC',
 'TRNS:INC_EFFICIENCY_NON_ELECTRIC',
 'TRNS:INC_OCCUPANCY_LIGHT_DUTY',
 'TRNS:SHIFT_FUEL_LIGHT_DUTY',
 'TRNS:SHIFT_FUEL_MARITIME',
 'TRNS:SHIFT_FUEL_MEDIUM_DUTY',
 'TRNS:SHIFT_FUEL_RAIL',
 'TRNS:SHIFT_MODE_FREIGHT',
 'TRNS:SHIFT_MODE_PASSENGER',
 'TRNS:SHIFT_MODE_REGIONAL',
 'TRWW:INC_CAPTURE_BIOGAS',
 'TRWW:INC_COMPLIANCE_SEPTIC',
 'WALI:INC_TREATMENT_INDUSTRIAL',
 'WALI:INC_TREATMENT_RURAL',
 'WALI:INC_TREATMENT_URBAN',
 'WASO:DEC_CONSUMER_FOOD_WASTE_HIGHEST',
 'WASO:INC_ANAEROBIC_AND_COMPOST',
 'WASO:INC_CAPTURE_BIOGAS',
 'WASO:INC_ENERGY_FROM_BIOGAS',
 'WASO:INC_ENERGY_FROM_INCINERATION',
 'WASO:INC_LANDFILLING',
 'WASO:INC_RECYCLING']

In [14]:
df_attr_strat = pd.read_csv('data/ssp_model_results/iran/ATTRIBUTE_STRATEGY_new.csv')
df_attr_strat.head()

,strategy_id,strategy_code,strategy,description,transformation_specification,baseline_strategy_id
0,0,BASE,Strategy TX:BASE,NaN,TX:BASE,1
1,1000,AGRC:DEC_CH4_RICE,Singleton - Default Value - AGRC: Improve rice...,NaN,TX:AGRC:DEC_CH4_RICE,0
2,1001,AGRC:DEC_EXPORTS,Singleton - Default Value - AGRC: Decrease Exp...,NaN,TX:AGRC:DEC_EXPORTS,0
3,1002,AGRC:DEC_LOSSES_SUPPLY_CHAIN,Singleton - Default Value - AGRC: Reduce suppl...,NaN,TX:AGRC:DEC_LOSSES_SUPPLY_CHAIN,0
4,1003,AGRC:INC_CONSERVATION_AGRICULTURE,Singleton - Default Value - AGRC: Expand conse...,NaN,TX:AGRC:INC_CONSERVATION_AGRICULTURE,0

In [15]:
df_attr_strat['strategy_code'] = df_attr_strat['strategy_code'].apply(lambda x: ":".join(x.split(":")[1:]) if x.split(":")[0] == 'TORNADO' else x)
df_attr_strat.tail()

,strategy_id,strategy_code,strategy,description,transformation_specification,baseline_strategy_id
133,7057,WASO:INC_CAPTURE_BIOGAS,TORNADO:WASO:INC_CAPTURE_BIOGAS,NaN,TX:WASO:INC_CAPTURE_BIOGAS|TX:LNDU:PLUR,0
134,7058,WASO:INC_ENERGY_FROM_BIOGAS,TORNADO:WASO:INC_ENERGY_FROM_BIOGAS,NaN,TX:WASO:INC_ENERGY_FROM_BIOGAS|TX:LNDU:PLUR,0
135,7059,WASO:INC_ENERGY_FROM_INCINERATION,TORNADO:WASO:INC_ENERGY_FROM_INCINERATION,NaN,TX:WASO:INC_ENERGY_FROM_INCINERATION|TX:LNDU:PLUR,0
136,7060,WASO:INC_LANDFILLING,TORNADO:WASO:INC_LANDFILLING,NaN,TX:WASO:INC_LANDFILLING|TX:LNDU:PLUR,0
137,7061,WASO:INC_RECYCLING,TORNADO:WASO:INC_RECYCLING,NaN,TX:WASO:INC_RECYCLING|TX:LNDU:PLUR,0

In [20]:
df_attr_strat_unique = df_attr_strat.drop_duplicates(subset='strategy_code', keep='last')

In [21]:
df_attr_strat_unique.to_csv('data/ssp_model_results/iran/ATTRIBUTE_STRATEGY_new.csv', index=False)

In [31]:
# List of suffixes to remove

df = pd.read_csv('data/ssp_model_results/iran/ATTRIBUTE_STRATEGY_new.csv')

suffixes_to_remove = [
    "_LOW", "_LOWEST", "_HIGHEST", "_HIGHER", "_HIGH", "_LOWER",
    "_FROMTECH", "_URBPLAN"
]

# Function to remove suffixes from a single transformation specification string
def clean_transformation_specification(specification):
    transformations = specification.split('|')  # Split by |
    cleaned_transformations = [
        t.rstrip(''.join(suffix for suffix in suffixes_to_remove if t.endswith(suffix)))
        for t in transformations
    ]
    return '|'.join(cleaned_transformations)

# Apply the function to the `transformation_specification` column
df['transformation_specification'] = df['transformation_specification'].apply(clean_transformation_specification)

# Save the updated DataFrame to a new CSV file
df.to_csv('data/ssp_model_results/iran/ATTRIBUTE_STRATEGY_new.csv', index=False)

print("The file has been updated and saved as 'updated_file.csv'.")

The file has been updated and saved as 'updated_file.csv'.